//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social_Diplon
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_information
    {
        public int user_id { get; set; }
        public int contact_type_id { get; set; }
        public string information { get; set; }
    
        public virtual contact_type contact_type { get; set; }
        public virtual user_open_information user_open_information { get; set; }
    }
}
