//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social_Diplon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a3cf84_akkara2Entities : DbContext
    {
        public db_a3cf84_akkara2Entities()
            : base("name=db_a3cf84_akkara2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<contact_type> contact_type { get; set; }
        public virtual DbSet<group_post> group_post { get; set; }
        public virtual DbSet<group_post_сomment> group_post_сomment { get; set; }
        public virtual DbSet<group_status> group_status { get; set; }
        public virtual DbSet<groups> groups { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<message_status> message_status { get; set; }
        public virtual DbSet<profession> profession { get; set; }
        public virtual DbSet<sex> sex { get; set; }
        public virtual DbSet<talk> talk { get; set; }
        public virtual DbSet<task> task { get; set; }
        public virtual DbSet<user_close_information> user_close_information { get; set; }
        public virtual DbSet<user_open_information> user_open_information { get; set; }
        public virtual DbSet<user_post> user_post { get; set; }
        public virtual DbSet<user_post_сomment> user_post_сomment { get; set; }
        public virtual DbSet<user_status> user_status { get; set; }
        public virtual DbSet<complete_task> complete_task { get; set; }
        public virtual DbSet<contact_information> contact_information { get; set; }
    }
}
