//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social_Diplon
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_post_сomment
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int group_post_id { get; set; }
        public string user_text { get; set; }
        public string sending_time { get; set; }
    
        public virtual group_post group_post { get; set; }
        public virtual user_open_information user_open_information { get; set; }
    }
}
