//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social_Diplon
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int id { get; set; }
        public int talk_id { get; set; }
        public int user_id { get; set; }
        public string user_text { get; set; }
        public System.DateTime sending_time { get; set; }
        public Nullable<int> message_status_id { get; set; }
    
        public virtual user_open_information user_open_information { get; set; }
        public virtual talk talk { get; set; }
        public virtual message_status message_status { get; set; }
    }
}
